USE customer_behavior;
GO
--Q1. What is the total revenue generated by male vs female customers?
SELECT 
    gender,
    SUM(purchase_amount) AS revenue
FROM dbo.customer_shopping_behavior
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchases amoung?
SELECT 
    customer_id,
    purchase_amount
FROM dbo.customer_shopping_behavior
WHERE discount_applied = 'Yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM dbo.customer_shopping_behavior
);

--Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5
    item_purchased,
    ROUND(AVG(review_rating),2) AS Average_Product_Rating
FROM dbo.customer_shopping_behavior
GROUP BY item_purchased
ORDER BY Average_Product_Rating DESC;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM dbo.customer_shopping_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscibed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
    subscription_status,
    COUNT(customer_id) as total_customers,
    ROUND(AVG(purchase_amount),2) AS average_spend,
    ROUND(SUM(purchase_amount),2) AS total_revenue
FROM dbo.customer_shopping_behavior
GROUP BY subscription_status
ORDER BY total_revenue, average_spend DESC;

--Q6. Which 5 Products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
    item_purchased,
    CAST(
        ROUND(
            SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
            2
        ) AS DECIMAL(10,2)
    ) AS discount_rate
FROM dbo.customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM dbo.customer_shopping_behavior
)

SELECT
    customer_segment,
    COUNT(*) AS Number_of_Customers
FROM customer_type
GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM dbo.customer_shopping_behavior
    GROUP BY category, item_purchased
)

SELECT
    category,
    item_rank,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM dbo.customer_shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10. What is the revenue contribution of each age group?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM dbo.customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;